/*
 * This file is generated by jOOQ.
 */
package com.agency360.listing.model.tables.records;


import com.agency360.listing.model.tables.Listing;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListingRecord extends UpdatableRecordImpl<ListingRecord> implements Record6<Integer, Integer, String, Long, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.listing.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.listing.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.listing.dealer_id</code>.
     */
    public void setDealerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.listing.dealer_id</code>.
     */
    public Integer getDealerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.listing.vehicule</code>.
     */
    public void setVehicule(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.listing.vehicule</code>.
     */
    public String getVehicule() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.listing.price</code>.
     */
    public void setPrice(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.listing.price</code>.
     */
    public Long getPrice() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.listing.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.listing.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.listing.state</code>.
     */
    public void setState(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.listing.state</code>.
     */
    public String getState() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, Long, LocalDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, Long, LocalDateTime, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Listing.LISTING.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Listing.LISTING.DEALER_ID;
    }

    @Override
    public Field<String> field3() {
        return Listing.LISTING.VEHICULE;
    }

    @Override
    public Field<Long> field4() {
        return Listing.LISTING.PRICE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Listing.LISTING.CREATED_AT;
    }

    @Override
    public Field<String> field6() {
        return Listing.LISTING.STATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getDealerId();
    }

    @Override
    public String component3() {
        return getVehicule();
    }

    @Override
    public Long component4() {
        return getPrice();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public String component6() {
        return getState();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getDealerId();
    }

    @Override
    public String value3() {
        return getVehicule();
    }

    @Override
    public Long value4() {
        return getPrice();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public String value6() {
        return getState();
    }

    @Override
    public ListingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ListingRecord value2(Integer value) {
        setDealerId(value);
        return this;
    }

    @Override
    public ListingRecord value3(String value) {
        setVehicule(value);
        return this;
    }

    @Override
    public ListingRecord value4(Long value) {
        setPrice(value);
        return this;
    }

    @Override
    public ListingRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ListingRecord value6(String value) {
        setState(value);
        return this;
    }

    @Override
    public ListingRecord values(Integer value1, Integer value2, String value3, Long value4, LocalDateTime value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListingRecord
     */
    public ListingRecord() {
        super(Listing.LISTING);
    }

    /**
     * Create a detached, initialised ListingRecord
     */
    public ListingRecord(Integer id, Integer dealerId, String vehicule, Long price, LocalDateTime createdAt, String state) {
        super(Listing.LISTING);

        setId(id);
        setDealerId(dealerId);
        setVehicule(vehicule);
        setPrice(price);
        setCreatedAt(createdAt);
        setState(state);
    }

    /**
     * Create a detached, initialised ListingRecord
     */
    public ListingRecord(com.agency360.listing.model.tables.pojos.Listing value) {
        super(Listing.LISTING);

        if (value != null) {
            setId(value.getId());
            setDealerId(value.getDealerId());
            setVehicule(value.getVehicule());
            setPrice(value.getPrice());
            setCreatedAt(value.getCreatedAt());
            setState(value.getState());
        }
    }
}
