/*
 * This file is generated by jOOQ.
 */
package com.agency360.listing.model.tables.records;


import com.agency360.listing.model.tables.TierLimit;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TierLimitRecord extends UpdatableRecordImpl<TierLimitRecord> implements Record3<Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tier_limit.dealer_id</code>.
     */
    public void setDealerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tier_limit.dealer_id</code>.
     */
    public Integer getDealerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tier_limit.listing_limit</code>.
     */
    public void setListingLimit(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tier_limit.listing_limit</code>.
     */
    public Integer getListingLimit() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tier_limit.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tier_limit.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TierLimit.TIER_LIMIT.DEALER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return TierLimit.TIER_LIMIT.LISTING_LIMIT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return TierLimit.TIER_LIMIT.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getDealerId();
    }

    @Override
    public Integer component2() {
        return getListingLimit();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getDealerId();
    }

    @Override
    public Integer value2() {
        return getListingLimit();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public TierLimitRecord value1(Integer value) {
        setDealerId(value);
        return this;
    }

    @Override
    public TierLimitRecord value2(Integer value) {
        setListingLimit(value);
        return this;
    }

    @Override
    public TierLimitRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TierLimitRecord values(Integer value1, Integer value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TierLimitRecord
     */
    public TierLimitRecord() {
        super(TierLimit.TIER_LIMIT);
    }

    /**
     * Create a detached, initialised TierLimitRecord
     */
    public TierLimitRecord(Integer dealerId, Integer listingLimit, LocalDateTime createdAt) {
        super(TierLimit.TIER_LIMIT);

        setDealerId(dealerId);
        setListingLimit(listingLimit);
        setCreatedAt(createdAt);
    }

    /**
     * Create a detached, initialised TierLimitRecord
     */
    public TierLimitRecord(com.agency360.listing.model.tables.pojos.TierLimit value) {
        super(TierLimit.TIER_LIMIT);

        if (value != null) {
            setDealerId(value.getDealerId());
            setListingLimit(value.getListingLimit());
            setCreatedAt(value.getCreatedAt());
        }
    }
}
