/*
 * This file is generated by jOOQ.
 */
package com.agency360.listing.model.tables.records;


import com.agency360.listing.model.tables.TierLimit;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TierLimitRecord extends UpdatableRecordImpl<TierLimitRecord> implements Record5<Integer, Integer, Integer, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tier_limit.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tier_limit.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tier_limit.dealer_id</code>.
     */
    public void setDealerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tier_limit.dealer_id</code>.
     */
    public Integer getDealerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tier_limit.listing_limit</code>.
     */
    public void setListingLimit(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tier_limit.listing_limit</code>.
     */
    public Integer getListingLimit() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.tier_limit.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tier_limit.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tier_limit.when_done</code>.
     */
    public void setWhenDone(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tier_limit.when_done</code>.
     */
    public LocalDateTime getWhenDone() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TierLimit.TIER_LIMIT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TierLimit.TIER_LIMIT.DEALER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return TierLimit.TIER_LIMIT.LISTING_LIMIT;
    }

    @Override
    public Field<String> field4() {
        return TierLimit.TIER_LIMIT.WHO_DONE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TierLimit.TIER_LIMIT.WHEN_DONE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getDealerId();
    }

    @Override
    public Integer component3() {
        return getListingLimit();
    }

    @Override
    public String component4() {
        return getWhoDone();
    }

    @Override
    public LocalDateTime component5() {
        return getWhenDone();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getDealerId();
    }

    @Override
    public Integer value3() {
        return getListingLimit();
    }

    @Override
    public String value4() {
        return getWhoDone();
    }

    @Override
    public LocalDateTime value5() {
        return getWhenDone();
    }

    @Override
    public TierLimitRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TierLimitRecord value2(Integer value) {
        setDealerId(value);
        return this;
    }

    @Override
    public TierLimitRecord value3(Integer value) {
        setListingLimit(value);
        return this;
    }

    @Override
    public TierLimitRecord value4(String value) {
        setWhoDone(value);
        return this;
    }

    @Override
    public TierLimitRecord value5(LocalDateTime value) {
        setWhenDone(value);
        return this;
    }

    @Override
    public TierLimitRecord values(Integer value1, Integer value2, Integer value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TierLimitRecord
     */
    public TierLimitRecord() {
        super(TierLimit.TIER_LIMIT);
    }

    /**
     * Create a detached, initialised TierLimitRecord
     */
    public TierLimitRecord(Integer id, Integer dealerId, Integer listingLimit, String whoDone, LocalDateTime whenDone) {
        super(TierLimit.TIER_LIMIT);

        setId(id);
        setDealerId(dealerId);
        setListingLimit(listingLimit);
        setWhoDone(whoDone);
        setWhenDone(whenDone);
    }

    /**
     * Create a detached, initialised TierLimitRecord
     */
    public TierLimitRecord(com.agency360.listing.model.tables.pojos.TierLimit value) {
        super(TierLimit.TIER_LIMIT);

        if (value != null) {
            setId(value.getId());
            setDealerId(value.getDealerId());
            setListingLimit(value.getListingLimit());
            setWhoDone(value.getWhoDone());
            setWhenDone(value.getWhenDone());
        }
    }
}
