/*
 * This file is generated by jOOQ.
 */
package com.agency360.listing.model.tables.daos;


import com.agency360.listing.model.tables.Dealer;
import com.agency360.listing.model.tables.records.DealerRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class DealerDao extends DAOImpl<DealerRecord, com.agency360.listing.model.tables.pojos.Dealer, Integer> {

    /**
     * Create a new DealerDao without any configuration
     */
    public DealerDao() {
        super(Dealer.DEALER, com.agency360.listing.model.tables.pojos.Dealer.class);
    }

    /**
     * Create a new DealerDao with an attached configuration
     */
    @Autowired
    public DealerDao(Configuration configuration) {
        super(Dealer.DEALER, com.agency360.listing.model.tables.pojos.Dealer.class, configuration);
    }

    @Override
    public Integer getId(com.agency360.listing.model.tables.pojos.Dealer object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.agency360.listing.model.tables.pojos.Dealer> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Dealer.DEALER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.agency360.listing.model.tables.pojos.Dealer> fetchById(Integer... values) {
        return fetch(Dealer.DEALER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.agency360.listing.model.tables.pojos.Dealer fetchOneById(Integer value) {
        return fetchOne(Dealer.DEALER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.agency360.listing.model.tables.pojos.Dealer> fetchOptionalById(Integer value) {
        return fetchOptional(Dealer.DEALER.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.agency360.listing.model.tables.pojos.Dealer> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Dealer.DEALER.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.agency360.listing.model.tables.pojos.Dealer> fetchByName(String... values) {
        return fetch(Dealer.DEALER.NAME, values);
    }
}
