/*
 * This file is generated by jOOQ.
 */
package com.agency360.listing.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dealer implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;

    public Dealer() {}

    public Dealer(Dealer value) {
        this.id = value.id;
        this.name = value.name;
    }

    public Dealer(
        Integer id,
        String  name
    ) {
        this.id = id;
        this.name = name;
    }

    /**
     * Getter for <code>public.dealer.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.dealer.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.dealer.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.dealer.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Dealer (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
