/*
 * This file is generated by jOOQ.
 */
package com.agency360.listing.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Listing implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       dealerId;
    private Long          price;
    private LocalDateTime createdAt;
    private String        state;

    public Listing() {}

    public Listing(Listing value) {
        this.id = value.id;
        this.dealerId = value.dealerId;
        this.price = value.price;
        this.createdAt = value.createdAt;
        this.state = value.state;
    }

    public Listing(
        Integer       id,
        Integer       dealerId,
        Long          price,
        LocalDateTime createdAt,
        String        state
    ) {
        this.id = id;
        this.dealerId = dealerId;
        this.price = price;
        this.createdAt = createdAt;
        this.state = state;
    }

    /**
     * Getter for <code>public.listing.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.listing.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.listing.dealer_id</code>.
     */
    public Integer getDealerId() {
        return this.dealerId;
    }

    /**
     * Setter for <code>public.listing.dealer_id</code>.
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * Getter for <code>public.listing.price</code>.
     */
    public Long getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>public.listing.price</code>.
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * Getter for <code>public.listing.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.listing.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.listing.state</code>.
     */
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>public.listing.state</code>.
     */
    public void setState(String state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Listing (");

        sb.append(id);
        sb.append(", ").append(dealerId);
        sb.append(", ").append(price);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(state);

        sb.append(")");
        return sb.toString();
    }
}
