/*
 * This file is generated by jOOQ.
 */
package com.agency360.listing.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TierLimit implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       dealerId;
    private Integer       listingLimit;
    private String        whoDone;
    private LocalDateTime whenDone;

    public TierLimit() {}

    public TierLimit(TierLimit value) {
        this.id = value.id;
        this.dealerId = value.dealerId;
        this.listingLimit = value.listingLimit;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
    }

    public TierLimit(
        Integer       id,
        Integer       dealerId,
        Integer       listingLimit,
        String        whoDone,
        LocalDateTime whenDone
    ) {
        this.id = id;
        this.dealerId = dealerId;
        this.listingLimit = listingLimit;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
    }

    /**
     * Getter for <code>public.tier_limit.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tier_limit.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.tier_limit.dealer_id</code>.
     */
    public Integer getDealerId() {
        return this.dealerId;
    }

    /**
     * Setter for <code>public.tier_limit.dealer_id</code>.
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * Getter for <code>public.tier_limit.listing_limit</code>.
     */
    public Integer getListingLimit() {
        return this.listingLimit;
    }

    /**
     * Setter for <code>public.tier_limit.listing_limit</code>.
     */
    public void setListingLimit(Integer listingLimit) {
        this.listingLimit = listingLimit;
    }

    /**
     * Getter for <code>public.tier_limit.who_done</code>.
     */
    public String getWhoDone() {
        return this.whoDone;
    }

    /**
     * Setter for <code>public.tier_limit.who_done</code>.
     */
    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    /**
     * Getter for <code>public.tier_limit.when_done</code>.
     */
    public LocalDateTime getWhenDone() {
        return this.whenDone;
    }

    /**
     * Setter for <code>public.tier_limit.when_done</code>.
     */
    public void setWhenDone(LocalDateTime whenDone) {
        this.whenDone = whenDone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TierLimit (");

        sb.append(id);
        sb.append(", ").append(dealerId);
        sb.append(", ").append(listingLimit);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);

        sb.append(")");
        return sb.toString();
    }
}
