/*
 * This file is generated by jOOQ.
 */
package com.agency360.listing.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TierLimit implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       dealerId;
    private Integer       listingLimit;
    private LocalDateTime createdAt;

    public TierLimit() {}

    public TierLimit(TierLimit value) {
        this.dealerId = value.dealerId;
        this.listingLimit = value.listingLimit;
        this.createdAt = value.createdAt;
    }

    public TierLimit(
        Integer       dealerId,
        Integer       listingLimit,
        LocalDateTime createdAt
    ) {
        this.dealerId = dealerId;
        this.listingLimit = listingLimit;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.tier_limit.dealer_id</code>.
     */
    public Integer getDealerId() {
        return this.dealerId;
    }

    /**
     * Setter for <code>public.tier_limit.dealer_id</code>.
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * Getter for <code>public.tier_limit.listing_limit</code>.
     */
    public Integer getListingLimit() {
        return this.listingLimit;
    }

    /**
     * Setter for <code>public.tier_limit.listing_limit</code>.
     */
    public void setListingLimit(Integer listingLimit) {
        this.listingLimit = listingLimit;
    }

    /**
     * Getter for <code>public.tier_limit.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.tier_limit.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TierLimit (");

        sb.append(dealerId);
        sb.append(", ").append(listingLimit);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
