/*
 * This file is generated by jOOQ.
 */
package com.agency360.listing.model;


import com.agency360.listing.model.tables.Dealer;
import com.agency360.listing.model.tables.Listing;
import com.agency360.listing.model.tables.TierLimit;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.dealer</code>.
     */
    public static final Dealer DEALER = Dealer.DEALER;

    /**
     * The table <code>public.listing</code>.
     */
    public static final Listing LISTING = Listing.LISTING;

    /**
     * The table <code>public.tier_limit</code>.
     */
    public static final TierLimit TIER_LIMIT = TierLimit.TIER_LIMIT;
}
